### ISSUE TITLE
i18n.js v4 plan

### ISSUE THREAD

**Issue by fnando** [fnando/i18n-js#590]
<br>
<br>
<br>
<p align="center">
  <img width="250" height="58" src="https://github.com/fnando/i18n-js/raw/main/i18njs.png" alt="i18n.js">
</p>

# About v4

It's been 4 years since I proposed a new direction for i18n.js on #399. Now, it's time to really act on it. 

The first commit is from [11 years ago](83b15531d07b8ab038de5bfbbaecbc8674c570ea), and most of what we have right now can be removed. Asset pipeline is dead, and we should embrace webpack/webpacker as the new way of writing JavaScript on Rails apps. It's fine if you don't like it and want to keep doing things in a different way, but this package will embrace Rails' philosophy.

This means that changes on how we interact with i18n.js will land on v4. Most of #399 stands true; I like the approach of having a CLI more than hacking my way in with a middleware that has performance problems (to be fair, I never thought people would use that middleware in production 🤯). Most bugs are related to how translations are exported, either though the middleware or rake task.

I've been using a few projects instead of i18n-js because I wanted a leaner way of doing things. These projects are:

- https://github.com/fnando/i18n: The NPM package, with TypeScript annotations and a modern stack.
- ~https://github.com/fnando/i18n-json: The CLI that can export translations based on a YAML file.~ This code has been merged to this repository on [v4](https://github.com/i18n-js/tree/v4) branch.
- https://github.com/fnando/glob: The package that allows filtering out hashes based on patterns.

I put up examples at https://github.com/fnando/i18n-js-examples that show how things are integrated. The sample Rails app, for instance, we leverages [listen](https://rubygems.org/gems/listen) in development to automatically export translations whenever we detect changes on both the YAML configuration and translation directory. For production, we can use `i18n export` as part of the build process.

# Next steps

I'll create a new branch [v4](https://github.com/fnando/i18n-js/tree/v4) and will integrate the code from i18n-json. This is, in my opinion, the bulk of Ruby code that will be required, but it's quite small.

```console
$ cloc i18n-json/lib
      11 text files.
      11 unique files.
       1 file ignored.

github.com/AlDanial/cloc v 1.88  T=0.01 s (1012.7 files/s, 55296.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Ruby                            10            119             11            416
-------------------------------------------------------------------------------
SUM:                            10            119             11            416
-------------------------------------------------------------------------------
```

glob is also small, but given its generic nature, I've decided to keep it on a separate gem.

```console
$ cloc glob/lib
       6 text files.
       6 unique files.
       0 files ignored.

github.com/AlDanial/cloc v 1.88  T=0.01 s (544.3 files/s, 14061.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Ruby                             6             24              6            125
-------------------------------------------------------------------------------
SUM:                             6             24              6            125
-------------------------------------------------------------------------------
```

The TypeScript code will live on its own branch from now on, which allows for a faster development cycle. There are more functions I'd like to add to it, and TypeScript annotations makes easier/safer to do it so. There is more code than before, because I already fixed some bugs and added a few new features.

```console
$ cloc i18n/src
      19 text files.
      19 unique files.
       0 files ignored.

github.com/AlDanial/cloc v 1.88  T=0.03 s (567.2 files/s, 54031.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                      19            216            612            982
-------------------------------------------------------------------------------
SUM:                            19            216            612            982
-------------------------------------------------------------------------------
```

# Task list

- [ ] Make it work with Heroku, DigitalOcean and Vercel with minimum configuration (just because they all build your project somehow)
- [ ] Document lazy loading of translations (webpack's [`import()`](https://webpack.js.org/guides/lazy-loading/) seems the way to go)
- [ ] Document code splitting techniques
- [ ] Document SSR translation
- [x] Write troubleshooting section ([empty json errors](https://github.com/fnando/i18n-js/issues/513), [custom backends](https://github.com/fnando/i18n-js/issues/59), [flat structure](https://github.com/fnando/i18n-js/issues/476), etc)
- [x] [Documentation](https://fnando.github.io/i18n/)
- [x] Implement `number_to_currency` using latest Rails API
- [x] Implement `number_to_percentage` using latest Rails API
- [x] Implement `number_to_human_size` using latest Rails API
- [x] Implement `number_to_delimited`
- [x] Implement `number_to_rounded`
- [x] Implement `number_to_human`
- [x] Revise YAML options, and use more sane defaults
- [x] ~Support for JSON transformation~ The recommendation is using the Ruby API or running commands after `i18n export`
- [x] [Support for key case transformation] (client-side only)(https://github.com/fnando/i18n/commit/d48ce75aab36ae413c29a46e7e66f30975744df1)
- [x] Investigate other i18n backends like Chain, Redis, and more
- [x] Go through all issues and either act on it or close them
- [x] [NPM package](https://github.com/fnando/i18n) using TypeScript
- [x] Export translations to separate files (e.g. `en` to `app/javascript/locales/en.json`, `pt-BR` to `app/javascript/locales/pt-BR.json`)
- [x] Fix bugs related to JavaScript and BigDecimal
- [x] Merge loaded translations, instead of requiring one single exported file
- [x] Ensure exported files are all sorted
- [x] [guard](https://rubygems.org/gems/guard) to export translations

To be clear: I don't intend to maintain anything related to asset pipeline anymore; if you rely on it and can't migrate to webpacker for any reason, you can either use v3 or create your own package to deal with it.

# How you can help

* Please test all releases and if you have any use case not covered by the feature list, post a comment.
* If you or your company use i18n.js, please considering becoming a [sponsor](https://github.com/sponsors/fnando).

# Some stats

![Around 9MM downloads](https://img.shields.io/npm/dt/i18n-js.svg?label=npm) ![Around 12MM downloads](https://img.shields.io/gem/dt/i18n-js.svg?label=gem&color=db6343)

# Feedback

Your feedback is very welcomed. If you have a feature request, would like to suggest a different plan, have some concern, or just on to say hi, please hit the comment button below.

**Comment by fnando** [comment]
Hey! I finally release an alpha version this. Please check this [announcement](https://github.com/fnando/i18n-js/discussions/609). 🎉🥳🍾🎊

**Comment by harigopal** [comment]
I encountered an issue with the _listen_ feature, and created #616, with (what feels like) a hack that avoid it.

**Comment by fnando** [comment]
@PikachuEXE fyi, https://github.com/fnando/i18n-js/tree/v4 is now the default branch.

**Comment by fnando** [comment]
Closed by 641e793d1651beb3324c54596859f8d1c17500a8

**Comment by morgoth** [comment]
@fnando Congratulations on v4 release.
Is there any guide how to upgrade from v3?
